---
- hosts: init
  become: yes
  tasks:
    - name: Install global packages
      ansible.builtin.package:
        name: 
          - zsh
          - wget
          - git
          - whois
        state: present

- hosts: initlinux
  become: yes
  tasks:
    - name: Create a login user
      user:
        name: '{{ usr }}'
        # get it with mkpasswd --method=sha-512 for non mac
        #ansible-vault encrypt_string --vault-id sepidre@prompt 'sepidre_pwd' --name 'password'
        #password: '{{ usrpwd }}' #'$6$R/4YUut1qdGneQFy$oB7bNV0GUykAeT0Xab/Cf0ORvXuX8wdsaETFO3qiOBpmL23Eu6nb2BZe5So5iaMvRQDWnK019elmox3EHRj.w0'
        password: '$6$R/4YUut1qdGneQFy$oB7bNV0GUykAeT0Xab/Cf0ORvXuX8wdsaETFO3qiOBpmL23Eu6nb2BZe5So5iaMvRQDWnK019elmox3EHRj.w0'
        uid: 1001
        groups: # Empty by default, here we give it some groups
        - sudo
        - www-data
        - users
        state: present
        shell: /bin/zsh       # Defaults to /bin/bash
        system: no             # Defaults to no
        createhome: yes        # Defaults to yes
        home: /home/{{ usr }}  # Defaults to /home/<username>
- hosts: initmac
  become: yes
  tasks:
    - name: Create a login user
      user:
        name: '{{ usr }}'
        #ansible-vault encrypt_string --vault-id sepidreclean@prompt 'sepidre_pwd' --name 'password'
        #password: '{{ usrpwdmac }}'
        password: '1234'
        uid: 1001
        groups: # Empty by default, here we give it some groups
        - sudo
        - www-data
        - users
        state: present
        shell: /bin/zsh       # Defaults to /bin/bash
        system: no             # Defaults to no
        createhome: yes        # Defaults to yes
        home: /home/{{ usr }}  # Defaults to /home/<username>
- hosts: init
  become: yes
  tasks:        
    - name: install public keys
      ansible.posix.authorized_key:
        user: sepidre
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    - name: Validate the sudoers file before saving
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s