---
- hosts: all
  become: no
  tasks:   
    - name: Install neofetch
      become: yes
      package:
        name: 
          - neofetch
          - bat
          - zsh-syntax-highlighting
          - zsh-autosuggestions
        state: present
    - name: Install Pureztom
      shell: curl -fsSL https://raw.githubusercontent.com/sepidre/Ansible/main/UserRoot/install_shell.sh | bash